leader1.enabled: false
leader2.enabled: false
leader3.enabled: false
leader4.enabled: true

logging.level.com.transferwise.common.leaderselector: DEBUG

---

spring:
  profiles: node1

server:
  port:
    11223

---

spring:
  profiles: node2

server:
  port:
    11224
